import type { Metadata } from "next";
import {
  Bodoni_Moda,
  Caveat,
  Cormorant_Garamond,
  Fraunces,
  Jost,
  Karla,
  Work_Sans,
} from "next/font/google";
import "./globals.css";

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  weight: "500",
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

// Fonts for the coastal-light and midnight-edition theme token sets (see
// globals.css). Not the app's default look — loaded alongside Fraunces/Work
// Sans so both themes can be manually previewed via layout.tsx's
// hardcoded data-theme value ahead of a real theme picker.
const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  weight: "500",
});

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

const bodoniModa = Bodoni_Moda({
  variable: "--font-bodoni-moda",
  subsets: ["latin"],
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

// Used only for the Reflections polaroid cards' handwritten-caption look
// (see the Reflections section of /experiences/[id]) — not tied to any
// theme.
const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="editorial-classic"
      className={`${fraunces.variable} ${workSans.variable} ${cormorantGaramond.variable} ${karla.variable} ${bodoniModa.variable} ${jost.variable} ${caveat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
